### ISSUE TITLE
Implement a state machine for the facilities

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_api#11]
It should cater for:
- upgrades
- downgrades
- initial approval
- initial registration

There should be a status / transition log model, with the following:
- [ ] A field to record the `reason` for each transition
- [ ] A record 

Use page 15 of the implementation guide as a source.

**Comment by ngurenyaga** [comment]
The state transitions should be strict, and enforced at the lowest practical level ( models ).

**Comment by sombo09** [comment]
This will be a very nuanced state machine, esp. given the role of edits ( same facility record gets updated ).

**Comment by ngurenyaga** [comment]
Scope subsumed by new issue #93
