### ISSUE TITLE
The user profile or custom user model should be able to link a user to a county / subcounty

### ISSUE THREAD

**Issue by sombo09** [MasterFacilityList/mfl_api#24]
This will be the foundation of the mechanism by which access by users whose privileges are limited to accessing a specific county's behavior will be limited.

**Comment by ngurenyaga** [comment]
Consider also whether to assign to a ward or constituency.

**Comment by ngurenyaga** [comment]
PR https://github.com/MasterFacilityList/mfl_api/pull/87 addresses this.
