### ISSUE TITLE
Create a satellite model and API for facilities that will store regulation information

### ISSUE THREAD

**Issue by sombo09** [MasterFacilityList/mfl_api#29]
This will underpin the synchronization of the MFL and regulator systems.

**Comment by ngurenyaga** [comment]
The regulators of interest are:
- Kenya Medical Practitioners and Dentists Board
- Nursing Council of Kenya
- Clinical Officers Council
- Kenya Medical Laboratories Technicians and Technologists Board
- Pharmacy and Poisons Board
- Radiation Protection Board
- MOH-Director of Medical Services (through the Chief Health Administrative Officer)

A more definitive list can be found in the current system's database.

**Comment by ngurenyaga** [comment]
Handled in #30
