### ISSUE TITLE
Community Health Units

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_api#44]
Community Health Units are **linked to a facility**. 

Other data about them include:
- community codes ( "CU Code" )
- name
- date established
- county ( and other things e.g district, location )
- status -> fully functiona, semi operational, operational
# Background Information

The following background information on community health units will help place this in perspective:

**What is a Community Health Unit?**
This is a health service delivery structure within a defined geographical area covering a population of approximately 5,000 people. Each unit is assigned 2 Community Health Extension Workers (CHEWs) and community health volunteers who offer promotive, preventative and basic curative health services.

It is governed by a Community Health Committee (CHC) and each Community Health unit is linked to a specific Health facility.

**Why Community Health Units?**
To bring services closer to the people using innovative approaches that empower them to be responsible for their own health. 

**Services Available at Community Health Units (CHUs)**

a)      Water and sanitation hygiene; e.g. Faecal management, Household water treatment and demonstrations on hand washing with soap, etc. 
b)    Advise on maternal and child health e.g. Immunization, Individual birth plan, etc. 
c)   Provision of Family planning commodities. 
d)   Growth monitoring for children under 5 years. 
e)   Deworming of children. 
f)   Provision of Long Lasting Insecticide Treated Nets (LLITNs). 
g)   Management of diarrhea, injuries, wounds, jiggers and other minor illnesses. 
h)   Provision of Information, Education & Communication (IEC) materials 
i)   Defaulter tracing (ART, TB and Immunization) 
j)   Referrals to health facilities 
k)   First Aid Services

**Comment by ngurenyaga** [comment]
The current community health units system stores the following about each CHUL:
- code
- name 
- facility it is attached to: should be MFL, but the current data appears to be very dirty, with the "Chew_Facility" having mostly individuals names, and having no way to link back to MFL
- number of households monitored
- status
- approval information

The `mchul_maria` table in the current system seems to have the most important data with regard to link facilities. 

The `Chew_Facility` field will require further study / discussion.

**Comment by ngurenyaga** [comment]
The view `dbo.qryUnitsAll` may be very helpful.

**Comment by ngurenyaga** [comment]
@bmarika 

Confirm that the following were handled in PR #108 :
- [x] Community health units status e.g operational, not operational ( same as facilities )
- [x] CU Codes
- [ ] CHEW status 
- [x] CHEW number of household monitored
- [x] CHEW approval information

I recommend that you follow the ticket suggestion and study the `mchul_maria` and `dbo.ryUnitsAll` DDL, as recommended.

**Comment by bmarika** [comment]
The active field from abstract base could  be used to indicate whether a CHEW is active or not.
